baseclasses: fix compile error
sysclock.cpp(24): error C2440: 'initializing': cannot convert from 'const GUID *' to 'const WCHAR *'
sysclock.cpp(24): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
sysclock.cpp(24): error C2440: 'initializing': cannot convert from 'CUnknown *(__stdcall *)(LPUNKNOWN,HRESULT *)' to 'const CLSID *'
sysclock.cpp(24): note: There is no context in which this conversion is possible

Unclear how this ever worked. If we don't define FILTER_DLL
then we get undefined references to g_Templates from dllentry.cpp
and dllsetup.cpp where &g_Templates is used unconditionally.